version: '3'

services:
  web:
    build: ./web/
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
  composer:
    image: composer
    volumes:
      - ../app:/app
    command: ['composer', 'install']
